services:
  - type: web
    name: swipe-security-check
    env: node
    buildCommand: npm install
    startCommand: node server.js
    repo: https://github.com/sw-esports/SW-IPE.git
    branch: main
    autoDeploy: true
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
